issuer: https://token.actions.githubusercontent.com
subject: repo:Aj-vrod/github-notifier:ref:refs/heads/.*


permissions:
  contents: read
  workflows: write

# repositories:
#   - Aj-vrod/github-notifier
#   - Aj-vrod/bicho
