issuer: https://token.actions.githubusercontent.com
subject: repo:org@<owner-id>/repo@<repo-id>:ref:refs/heads/test/trigger-workflow


permissions:
  contents: read
  workflows: write

# repositories:
#   - Aj-vrod/github-notifier
#   - Aj-vrod/bicho
