name: "Create issue in bicho repository"

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  trigger:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write # Needed to federate tokens.
    steps:
      - name: Grab tmp token
        uses: octo-sts/action@v1.1.1
        id: octo-sts
        with:
          scope: Aj-vrod/github-notifier,Aj-vrod/bicho
          identity: dev

      - name: Trigger bicho workflow
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh workflow run "Post an Issue via CI" --repo Aj-vrod/bicho -f title="From github-notifier" -f body="Finally worked"
