name: "Create issue in bicho repository"

on:
  pull_request:
    types: [ labeled ]

jobs:
  trigger:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.
    steps:
      - name: Grab tmp token
        uses: octo-sts/action@v1.1.1
        id: octo-sts
        with:
          scope: Aj-vrod/github-notifier
          identity: dev

      - name: Trigger bicho workflow
        run: |
          gh workflow run "Post an Issue via CI" --repo Aj-vrod/bicho -f title="From github-notifier" -f body="Finally worked"
